netconfig: Do not remove custom /etc/{resolv,yp}.conf on uninstall
Fix spec file not remove custom /etc/{resolv,yp}.conf on uninstall
of sysconfig-netconfig, but only the symlinks to /run/netconfig
files created by netconfig or tmpfiles.d(5) (bsc#1263889).

diff --git a/sysconfig.spec.in b/sysconfig.spec.in
--- a/sysconfig.spec.in
+++ b/sysconfig.spec.in
@@ -1,7 +1,7 @@
 #
 # spec file for package sysconfig
 #
-# Copyright (c) 2025 SUSE LLC and contributors
+# Copyright (c) 2026 SUSE LLC and contributors
 #
 # All modifications and additions to the file contributed by third parties
 # remain the property of their copyright owners, unless otherwise agreed
@@ -199,10 +199,10 @@ EOF
 %{_tmpfilesdir}/netconfig.conf
 %ghost %attr(0755,root,root) %dir /run/netconfig
 %ghost %attr(0644,root,root) /run/netconfig/resolv.conf
-%ghost %attr(0644,root,root) /etc/resolv.conf
+%ghost %attr(0644,root,root) %config(noreplace) /etc/resolv.conf
 %if %{with nis}
 %ghost %attr(0644,root,root) /run/netconfig/yp.conf
-%ghost %attr(0644,root,root) /etc/yp.conf
+%ghost %attr(0644,root,root) %config(noreplace) /etc/yp.conf
 %endif
 
 %post -p /bin/bash
@@ -214,5 +214,16 @@ EOF
 
 %post netconfig -p /bin/bash
 %tmpfiles_create %{_tmpfilesdir}/netconfig.conf
+
+%postun netconfig -p /bin/bash
+if [ $1 -eq 0 ] ; then
+	# cleanup /etc/{resolv,yp}.conf symlinks on uninstall
+	case $(readlink -m /etc/resolv.conf 2>/dev/null) in
+	/run/netconfig/resolv.conf) rm -f /etc/resolv.conf || : ;;
+	esac
+	case $(readlink -m /etc/yp.conf 2>/dev/null) in
+	/run/netconfig/yp.conf) rm -f /etc/yp.conf || : ;;
+	esac
+fi
 
 %changelog
