ifup: always join the systemd network.service cgroup
When ifup were started manually/directly and not inside of
the systemd network.service start run, or partial restart
like "rcnetwork restart eth0" were used, systemd were not
considering e.g. the dhcp clients started this way as part
of the network.service (bnc#810354).

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -32,6 +32,63 @@ STAMPFILE_STUB="$RUN_FILES_BASE/new-stamp-"
 NETWORKMANAGER_BIN=/usr/sbin/NetworkManager
 NM_ONLINE_BIN=/usr/bin/nm-online
 
+SYSTEMD_CGROUP_DIR="/sys/fs/cgroup/systemd"
+NETWORK_SERVICE_CGROUP_DIR="${SYSTEMD_CGROUP_DIR}/system/network.service"
+NETWORK_SERVICE_CGROUP_TASKS="${NETWORK_SERVICE_CGROUP_DIR}/tasks"
+
+
+systemd_running ()
+{
+	# We simply test whether systemd cgroup hierarchy is mounted
+	# where we return 0, non-zero if not.
+	/bin/mountpoint -q "${SYSTEMD_CGROUP_DIR}"
+}
+
+systemd_booting () {
+	# returns 0 when we boot, 1 in running system
+	systemctl show -p ActiveState default.target | grep -qi inactive
+}
+
+nm_running () {
+	local MSG RET
+	test -x "$NETWORKMANAGER_BIN" || return
+	MSG=`checkproc $NETWORKMANAGER_BIN 2>&1`
+	RET=$?
+	info_mesg "$MSG"
+	return $RET
+}
+
+netcontrol_running ()
+{
+	test -f $NETWORK_RUNFILE
+}
+
+in_network_service_cgroup ()
+{
+	local pid dummy
+	if test -f "${NETWORK_SERVICE_CGROUP_TASKS}" ; then
+		while read pid dummy ; do
+			test "$pid" = "$$" && return 0
+		done < "${NETWORK_SERVICE_CGROUP_TASKS}"
+	fi
+	return 1
+}
+
+add_to_network_service_cgroup ()
+{
+	if test ! -d "${NETWORK_SERVICE_CGROUP_DIR}" ; then
+		systemd_running && \
+		mkdir -p ${NETWORK_SERVICE_CGROUP_DIR} || \
+		return 1
+	fi
+	if test -f "${NETWORK_SERVICE_CGROUP_TASKS}" ; then
+		echo "$$" > "${NETWORK_SERVICE_CGROUP_TASKS}" && \
+		return 0
+	fi
+	return 1
+}
+
+
 #
 # to test the next two functions:
 #
@@ -79,19 +136,6 @@ add_to_wordlist() {
 		l=(${l[@]} $a)
 	done
 	eval "$v='${l[@]}'"
-}
-
-nm_running () {
-	local MSG RET
-	test -x "$NETWORKMANAGER_BIN" || return
-	MSG=`checkproc $NETWORKMANAGER_BIN 2>&1`
-	RET=$?
-	info_mesg "$MSG"
-	return $RET
-}
-
-netcontrol_running() {
-	test -f $NETWORK_RUNFILE
 }
 
 is_valid_interface_name()
