Fixed wait for ipv6 duplicate address detection
Improved to not wait for link ready by default, because this breaks
the status of several interfaces (e.g. host-only bridges) and check
the ipv6 duplicate address detection only. IPv6 dad starts when the
link becomes up & ready, so this includes the link ready status.
The link ready check can be enabled on a per interface basis.
Fixed to not wait for each single interface separately in ifup, but
to wait for all together in /etc/init.d/network instead (bnc#697929).

diff --git a/scripts/network b/scripts/network
--- a/scripts/network
+++ b/scripts/network
@@ -674,8 +674,7 @@ status() {
 	for IFACE in $@; do
 		$FAKE /sbin/ifstatus $CONFIG $IFACE -o rc $CHECK $MODE
 		RET=$?
-		debug && printf "    %-9s returned %s\n" $IFACE $RET || \
-		         printf "    %-9s\n" $IFACE
+		debug && printf "    %-9s returned %s\n" $IFACE $RET
 		case $RET in
 			$R_SUCCESS|$R_BUSY)
 				# : $((R++))
@@ -745,8 +744,7 @@ case "$ACTION" in
 			done
 			$FAKE ifup $CONFIG $IFACE -o rc $MODE
 			RET=$?
-			debug && printf "    %-9s returned %s\n" $IFACE $RET || \
-			         printf "    %-9s\n" $IFACE
+			debug && printf "    %-9s returned %s\n" $IFACE $RET
 			case "$RET" in
 	 			$R_SUCCESS)
 	 				SUCCESS_IFACES="$SUCCESS_IFACES $IFACE"
@@ -831,7 +829,7 @@ case "$ACTION" in
 
 			debug "Time to wait: $((WAIT_FOR_INTERFACES - TTWAIT))"
 			if [ "$NEWLINE" != yes ] ; then
-				echo "Waiting for mandatory devices: $MANDATORY_DEVICES"
+				echo "Waiting for mandatory devices: ${MANDATORY_DEVICES//__NSC__/}"
 			fi
 			echo -n "$((WAIT_FOR_INTERFACES - TTWAIT)) "
 			NEWLINE=yes
@@ -861,7 +859,7 @@ case "$ACTION" in
 		debug SUCCESS_IFACES=$SUCCESS_IFACES
 		debug MANDATORY_DEVICES=$MANDATORY_DEVICES
 		debug FAILED=$FAILED
-
+		debug TTWAIT=$TTWAIT
 
 		if [ -z "$INTERFACE" ] ; then
 			for IFACE in $VIRTUAL_IFACES ; do
@@ -870,8 +868,7 @@ case "$ACTION" in
 				done
 				$FAKE ifup $CONFIG $IFACE -o rc $MODE
 				RET=$?
-				debug && printf "    %-9s returned %s\n" $IFACE $RET || \
-				         printf "    %-9s\n" $IFACE
+				debug && printf "    %-9s returned %s\n" $IFACE $RET
 				case "$RET" in
 		 			$R_SUCCESS)
 		 				SUCCESS_IFACES="$SUCCESS_IFACES $IFACE"
@@ -886,7 +883,7 @@ case "$ACTION" in
 					$R_NOCONFIG)
 						rc_failed 6
 						rc_status -v1
-						: $((FAILED++))
+						# : $((FAILED++))
 						;;
 		 			$R_NOTCONFIGURED|$R_INACTIVE)
 		 				SUCCESS_IFACES="$SUCCESS_IFACES $IFACE"
@@ -896,13 +893,69 @@ case "$ACTION" in
 		 			*)
 		 				rc_failed 7
 		 				rc_status -v1
-						: $((FAILED++))
+						# : $((FAILED++))
 		 				;;
 				esac
 				rc_reset
 			done
-		fi
 
+			LINE=""
+			NEWLINE=no
+			while true; do
+				debug ... still waiting for virtual devices:
+				debug SUCCESS_IFACES=$SUCCESS_IFACES
+				debug VIRTUAL_IFACES=$VIRTUAL_IFACES
+
+				TMP=$VIRTUAL_IFACES
+				VIRTUAL_IFACES=
+				for IFACE in $TMP ; do
+					for S in $SUCCESS_IFACES; do
+						test "$IFACE" = "$S" && continue 2
+					done
+					IFACE="`type_filter $IFACE`"
+					test -z "$IFACE" && continue
+					status -m $IFACE &>/dev/null
+					RET=$?
+					if [ $RET = 0 ] ; then
+						SUCCESS_IFACES="$SUCCESS_IFACES $IFACE"
+						if [ "$NEWLINE" = yes ] ; then
+							echo
+							NEWLINE=no
+						fi
+						status $IFACE
+						continue
+					fi
+					VIRTUAL_IFACES="$VIRTUAL_IFACES $IFACE"
+				done
+	
+				IFS=. read a b < /proc/uptime
+				TTWAIT2=$((a - (TTWAIT + `cat $NETWORK_RUNFILE`)))
+				test $TTWAIT2 -gt $((WAIT_FOR_INTERFACES)) \
+					-o -z "$VIRTUAL_IFACES" && break
+
+				debug "Time to wait: $((WAIT_FOR_INTERFACES - TTWAIT2))"
+				if [ "$NEWLINE" != yes ] ; then
+					echo "Waiting for virtual interfaces: $VIRTUAL_IFACES"
+				fi
+				echo -n "$((WAIT_FOR_INTERFACES - TTWAIT2)) "
+				NEWLINE=yes
+				sleep 1
+			done
+
+			if [ "$NEWLINE" = yes ] ; then
+				echo
+			fi
+
+			for IFACE in $VIRTUAL_IFACES; do
+				if [ -d /sys/class/net/$IFACE ] ; then
+					status -m $IFACE && continue
+					printf "    %-9s interface is not ready until now\n" $IFACE
+				fi
+				rc_failed
+				rc_status -v1
+				: $((FAILED++))
+			done
+		fi
 
 		rc_reset
 		if [ -z "$INTERFACE" ] ; then
@@ -940,8 +993,7 @@ case "$ACTION" in
 			# printf "    %-9s " $IFACE
 			$FAKE ifdown $CONFIG $IFACE -o rc $MODE
 			RET=$?
-			debug && printf "    %-9s returned %s\n" $IFACE $RET || \
-			         printf "    %-9s\n" $IFACE
+			debug && printf "    %-9s returned %s\n" $IFACE $RET
 			rc_failed $RET
 			case "$RET" in
 				$R_NODEV|$R_NOTCONFIGURED|$R_INACTIVE)
@@ -988,8 +1040,7 @@ case "$ACTION" in
 			fi
 			$FAKE ifdown $CONFIG $IFACE -o rc $MODE
 			RET=$?
-			debug && printf "    %-9s returned %s\n" $IFACE $RET || \
-			         printf "    %-9s\n" $IFACE
+			debug && printf "    %-9s returned %s\n" $IFACE $RET
 			rc_failed $RET
 			case "$RET" in
 				$R_NODEV|$R_NOTCONFIGURED|$R_INACTIVE)
